// @ts-nocheck
/**
 * ═══════════════════════════════════════════════════════════════════════
 * BD WIZARD PHASE 3 — Sequence engine
 *
 * A "sequence" is a multi-step outbound campaign one rep runs against one
 * contact at one brand. Cadences live in this file as plain TypeScript
 * data — adding a new cadence means adding a key to CADENCES, no schema
 * change required.
 *
 * The sequence engine is intentionally "stupid": each step has a single
 * scheduledFor timestamp. A cron at /api/cron/bd-sequence-tick walks
 * the table every hour, finds steps whose scheduledFor has passed, and
 * either:
 *   - generates a draft + creates a CrmTask (email, linkedin_dm, linkedin_connect, tradeshow)
 *   - executes the side effect immediately (paid → flag the brand)
 *
 * Per Andrew's locked decision (2026-04-20): "Always queue for review —
 * no auto-send ever". So even email steps just generate a draft and
 * park it on /acm/tasks. The rep clicks through to the wizard and hits
 * Send themselves. This file does NOT send anything.
 * ═══════════════════════════════════════════════════════════════════════
 */

import { prisma } from "@/lib/prisma";

/**
 * One step in a cadence. offsetDays is from sequence start (= when the rep
 * sent the first email via the wizard). Step 0 is always day 0.
 *
 * Channels:
 *   - "email"            — auto-drafted, queued for rep review
 *   - "linkedin_connect" — manual reminder; rep sends connect request in LI
 *   - "linkedin_dm"      — auto-drafted text; rep pastes into LI manually
 *   - "paid"             — system flips Brand.paidAudienceTagged = true
 *   - "tradeshow"        — manual reminder; "invite to next show"
 */
export type CadenceChannel = "email" | "linkedin_connect" | "linkedin_dm" | "paid" | "tradeshow";

export interface CadenceStep {
  index: number;
  channel: CadenceChannel;
  offsetDays: number;
  /** Short title for the rep-facing CrmTask. */
  taskTitle: (brandName: string, contactName: string) => string;
  /** Whether this step needs a draft generated by AI. */
  needsDraft: boolean;
  /** Whether this step auto-completes (no rep action needed). */
  autoComplete: boolean;
}

const lcName = (c: { firstName?: string; name?: string }) =>
  c.firstName || (c.name ? c.name.split(" ")[0] : "contact");

/**
 * The default 6-step long funnel — locked by Andrew on 2026-04-20.
 *
 *   D0  LI connect       manual          rep sends connect request in LI
 *   D2  Email             auto-drafted    THIS IS THE WIZARD'S FIRST SEND
 *   D5  LI DM             auto-drafted    rep pastes the text into LI
 *   D9  Email follow-up   auto-drafted    rep reviews + sends from wizard
 *   D14 Paid retargeting  system          flag the brand for ad audience
 *   D30 Tradeshow         manual          invite at next relevant show
 *
 * Day 0 is the day the wizard fired its first email. The LI connect step
 * is auto-skipped at sequence creation since the rep has already kicked
 * off contact via email — keeping it in the cadence so the dashboard
 * shows the full intended funnel even when steps got short-circuited.
 */
const DEFAULT_CADENCE: CadenceStep[] = [
  {
    index: 0,
    channel: "linkedin_connect",
    offsetDays: 0,
    taskTitle: (brand, contact) => `Send LinkedIn connect to ${contact} at ${brand}`,
    needsDraft: false,
    autoComplete: false,
  },
  {
    index: 1,
    channel: "email",
    offsetDays: 0, // first wizard send — same day as sequence creation
    taskTitle: (brand, contact) => `Email ${contact} at ${brand}`,
    needsDraft: true,
    autoComplete: false,
  },
  {
    index: 2,
    channel: "linkedin_dm",
    offsetDays: 5,
    taskTitle: (brand, contact) => `LinkedIn DM ${contact} at ${brand}`,
    needsDraft: true,
    autoComplete: false,
  },
  {
    index: 3,
    channel: "email",
    offsetDays: 9,
    taskTitle: (brand, contact) => `Email follow-up to ${contact} at ${brand}`,
    needsDraft: true,
    autoComplete: false,
  },
  {
    index: 4,
    channel: "paid",
    offsetDays: 14,
    taskTitle: (brand) => `Tag ${brand} for paid retargeting audience`,
    needsDraft: false,
    autoComplete: true,
  },
  {
    index: 5,
    channel: "tradeshow",
    offsetDays: 30,
    taskTitle: (brand, contact) => `Invite ${contact} (${brand}) to next FUZE tradeshow`,
    needsDraft: false,
    autoComplete: false,
  },
];

export const CADENCES: Record<string, CadenceStep[]> = {
  default: DEFAULT_CADENCE,
};

export function getCadence(key: string): CadenceStep[] {
  return CADENCES[key] || DEFAULT_CADENCE;
}

/** Hours between sequence ticks. The cron schedule in vercel.json should match. */
export const TICK_INTERVAL_HOURS = 1;

const HUMAN_CHANNEL: Record<CadenceChannel, string> = {
  email: "Email",
  linkedin_connect: "LinkedIn connect request",
  linkedin_dm: "LinkedIn DM",
  paid: "Paid retargeting",
  tradeshow: "Tradeshow invite",
};

export function humanChannel(c: string): string {
  return HUMAN_CHANNEL[c as CadenceChannel] || c;
}

/**
 * Create a sequence on the back of the wizard's first send. Called from
 * /api/admin/bd/wizard/send AFTER the first outbound has been dispatched
 * successfully and the OutreachMessage row has been written.
 *
 * Behavior:
 *   - If an active sequence already exists for (brand, contact, rep),
 *     no-op and return it. This is the second-time-the-rep-uses-the-
 *     wizard-on-the-same-contact case.
 *   - Otherwise create a sequence with one step per CadenceStep:
 *       step 0 (LI connect)  → status=skipped (we already opened with email)
 *       step 1 (email)       → status=sent, sentAt=now (the wizard just sent it)
 *       steps 2+             → status=pending, scheduledFor = startedAt + offset
 *
 * The transaction is passed in so the caller can commit it alongside the
 * wizard's own atomic writes.
 */
export async function createSequenceForFirstSend(opts: {
  tx: any; // Prisma transaction client
  brandId: string;
  contactId: string;
  repId: string;
  startedAt: Date;
  outreachMessageId?: string | null;
  /** Subject + body of the email that just went out — copied onto step 1 for history. */
  firstEmailSubject?: string | null;
  firstEmailBody?: string | null;
  cadenceKey?: string;
}) {
  const tx = opts.tx;
  const cadenceKey = opts.cadenceKey || "default";
  const cadence = getCadence(cadenceKey);

  // Bail if there's already an active sequence for this (brand, contact, rep).
  const existing = await tx.bDSequence.findFirst({
    where: {
      brandId: opts.brandId,
      contactId: opts.contactId,
      repId: opts.repId,
      status: "active",
    },
  });
  if (existing) return existing;

  const totalSteps = cadence.length;

  const seq = await tx.bDSequence.create({
    data: {
      brandId: opts.brandId,
      contactId: opts.contactId,
      repId: opts.repId,
      cadenceKey,
      status: "active",
      startedAt: opts.startedAt,
      totalSteps,
      sentSteps: 1, // step 1 (email) is sent
      skippedSteps: 1, // step 0 (LI connect) is skipped
    },
  });

  await Promise.all(
    cadence.map((step) => {
      const scheduledFor = new Date(
        opts.startedAt.getTime() + step.offsetDays * 24 * 60 * 60 * 1000,
      );

      // Step 0: LI connect — auto-skipped (we opened with email instead).
      if (step.index === 0) {
        return tx.bDSequenceStep.create({
          data: {
            sequenceId: seq.id,
            stepIndex: step.index,
            channel: step.channel,
            status: "skipped",
            scheduledFor,
            skippedAt: opts.startedAt,
            failReason: "Wizard opened with email — LinkedIn connect skipped at sequence creation.",
          },
        });
      }

      // Step 1: the email that just went out.
      if (step.index === 1) {
        return tx.bDSequenceStep.create({
          data: {
            sequenceId: seq.id,
            stepIndex: step.index,
            channel: step.channel,
            status: "sent",
            scheduledFor,
            sentAt: opts.startedAt,
            draftSubject: opts.firstEmailSubject || null,
            draftBody: opts.firstEmailBody || null,
            outreachMessageId: opts.outreachMessageId || null,
          },
        });
      }

      // Steps 2+: pending, waiting for the cron to tick them ready.
      return tx.bDSequenceStep.create({
        data: {
          sequenceId: seq.id,
          stepIndex: step.index,
          channel: step.channel,
          status: "pending",
          scheduledFor,
        },
      });
    }),
  );

  return seq;
}

/**
 * Mark a step as sent and recompute sequence counters. If this was the
 * last non-terminal step, mark the sequence completed. Caller must run
 * inside a transaction.
 */
export async function markStepSent(opts: {
  tx: any;
  stepId: string;
  outreachMessageId?: string | null;
  draftSubject?: string | null;
  draftBody?: string | null;
}) {
  const step = await opts.tx.bDSequenceStep.update({
    where: { id: opts.stepId },
    data: {
      status: "sent",
      sentAt: new Date(),
      outreachMessageId: opts.outreachMessageId ?? undefined,
      draftSubject: opts.draftSubject ?? undefined,
      draftBody: opts.draftBody ?? undefined,
    },
  });
  await recomputeSequenceCounters(opts.tx, step.sequenceId);
  return step;
}

/** Mark a step as skipped (rep declined to send) and bump counters. */
export async function markStepSkipped(opts: { tx: any; stepId: string; reason?: string }) {
  const step = await opts.tx.bDSequenceStep.update({
    where: { id: opts.stepId },
    data: {
      status: "skipped",
      skippedAt: new Date(),
      failReason: opts.reason || null,
    },
  });
  await recomputeSequenceCounters(opts.tx, step.sequenceId);
  return step;
}

/** Mark a step as failed (send error) and bump counters. */
export async function markStepFailed(opts: { tx: any; stepId: string; reason: string }) {
  const step = await opts.tx.bDSequenceStep.update({
    where: { id: opts.stepId },
    data: {
      status: "failed",
      failedAt: new Date(),
      failReason: opts.reason,
    },
  });
  await recomputeSequenceCounters(opts.tx, step.sequenceId);
  return step;
}

/**
 * Recompute sentSteps + skippedSteps + completion state for a sequence.
 * Called whenever a step changes terminal state. We do this server-side
 * rather than incrementing in place because the transaction guarantees
 * consistency even if multiple steps fire in parallel from cron.
 */
export async function recomputeSequenceCounters(tx: any, sequenceId: string) {
  const steps = await tx.bDSequenceStep.findMany({
    where: { sequenceId },
    select: { status: true },
  });
  const sent = steps.filter((s) => s.status === "sent").length;
  const skipped = steps.filter((s) => s.status === "skipped").length;
  const failed = steps.filter((s) => s.status === "failed").length;
  const terminal = sent + skipped + failed;
  const total = steps.length;

  const update: any = { sentSteps: sent, skippedSteps: skipped };
  if (terminal === total) {
    update.status = "completed";
    update.completedAt = new Date();
  }
  await tx.bDSequence.update({ where: { id: sequenceId }, data: update });
}

/**
 * Used by the wizard send route to detect "this is a follow-up step send,
 * not a brand-new outbound" — if the rep is sending against a step that
 * already exists, we mark the step sent rather than re-creating a sequence.
 */
export async function findStepForSend(opts: { brandId: string; contactId: string; repId: string }) {
  const seq = await prisma.bDSequence.findFirst({
    where: {
      brandId: opts.brandId,
      contactId: opts.contactId,
      repId: opts.repId,
      status: "active",
    },
    include: {
      steps: {
        where: { status: "ready", channel: { in: ["email", "linkedin_dm"] } },
        orderBy: { stepIndex: "asc" },
        take: 1,
      },
    },
  });
  return seq?.steps?.[0] || null;
}
