-- AlterTable: Add intake form fields to Fabric model
ALTER TABLE "Fabric" ADD COLUMN "endUse" TEXT,
ADD COLUMN "targetFuzeTier" TEXT,
ADD COLUMN "annualVolume" TEXT,
ADD COLUMN "batchLotNumber" TEXT,
ADD COLUMN "thickness" DOUBLE PRECISION,
ADD COLUMN "shrinkageLength" DOUBLE PRECISION,
ADD COLUMN "shrinkageWidth" DOUBLE PRECISION,
ADD COLUMN "fabricCategory" TEXT,
ADD COLUMN "knitStitchType" TEXT,
ADD COLUMN "weavePattern" TEXT,
ADD COLUMN "gauge" TEXT,
ADD COLUMN "threadCountWarp" INTEGER,
ADD COLUMN "threadCountWeft" INTEGER,
ADD COLUMN "pretreatment" JSONB,
ADD COLUMN "fabricPh" DOUBLE PRECISION,
ADD COLUMN "dyeApplied" BOOLEAN,
ADD COLUMN "dyeStage" TEXT,
ADD COLUMN "dyeClass" TEXT,
ADD COLUMN "dyeDetails" JSONB,
ADD COLUMN "finishSoftener" JSONB,
ADD COLUMN "finishRepellent" JSONB,
ADD COLUMN "finishWicking" JSONB,
ADD COLUMN "finishWrinkleFree" JSONB,
ADD COLUMN "finishOther" JSONB,
ADD COLUMN "intakeFormId" TEXT,
ADD COLUMN "intakeParsedAt" TIMESTAMP(3);
